/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/17.0/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak-nodejs-admin-client), as they take care of authetication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ``` 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthDetailsRepresentation
 */
export interface AuthDetailsRepresentation {
    /**
     * 
     * @type {string}
     * @memberof AuthDetailsRepresentation
     */
    realmId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthDetailsRepresentation
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthDetailsRepresentation
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthDetailsRepresentation
     */
    ipAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthDetailsRepresentation
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthDetailsRepresentation
     */
    sessionId?: string;
}

/**
 * Check if a given object implements the AuthDetailsRepresentation interface.
 */
export function instanceOfAuthDetailsRepresentation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthDetailsRepresentationFromJSON(json: any): AuthDetailsRepresentation {
    return AuthDetailsRepresentationFromJSONTyped(json, false);
}

export function AuthDetailsRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthDetailsRepresentation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'realmId': !exists(json, 'realmId') ? undefined : json['realmId'],
        'clientId': !exists(json, 'clientId') ? undefined : json['clientId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'ipAddress': !exists(json, 'ipAddress') ? undefined : json['ipAddress'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'sessionId': !exists(json, 'sessionId') ? undefined : json['sessionId'],
    };
}

export function AuthDetailsRepresentationToJSON(value?: AuthDetailsRepresentation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'realmId': value.realmId,
        'clientId': value.clientId,
        'userId': value.userId,
        'ipAddress': value.ipAddress,
        'username': value.username,
        'sessionId': value.sessionId,
    };
}

