/* tslint:disable */
/* eslint-disable */
/**
 * Phase Two Admin REST API
 * This is a REST API reference for the Phase Two Keycloak custom resources. These are extensions to the standard [Keycloak Admin REST API](https://www.keycloak.org/docs-api/17.0/rest-api/index.html).  ### Base URI format Paths specified in the documentation are relative to the the base URI. - Format: `https://<host>:<port>/auth/realms` - Example: `https://app.phasetwo.io/auth/realms`  ### Authentication Authentication is achieved by using the `Authentication: Bearer <token>` header in all requests. This is either the access token received from a normal authentication, or by a request directly to the OpenID Connect token endpoint.  It is recommended that you use a Keycloak Admin Client, such as [this one for Javascript](https://github.com/keycloak/keycloak-nodejs-admin-client), as they take care of authetication, getting an access token, and refreshing it when it expires.  #### Client credentials grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=client_credentials&client_id=admin-cli&client_secret=fd649804-3a74-4d69-acaa-8f065c6b7da1 ```  #### Password grant example ``` POST /auth/realms/test-realm/protocol/openid-connect/token Host: app.phasetwo.io Accept: application/json Content-type: application/x-www-form-urlencoded  grant_type=password&username=uname@foo.com&password=pwd123AZY&client_id=admin-cli ``` 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationDomainRepresentation
 */
export interface OrganizationDomainRepresentation {
    /**
     * 
     * @type {string}
     * @memberof OrganizationDomainRepresentation
     */
    domainName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationDomainRepresentation
     */
    verified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDomainRepresentation
     */
    recordKey?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDomainRepresentation
     */
    recordValue?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDomainRepresentation
     */
    type?: string;
}

/**
 * Check if a given object implements the OrganizationDomainRepresentation interface.
 */
export function instanceOfOrganizationDomainRepresentation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationDomainRepresentationFromJSON(json: any): OrganizationDomainRepresentation {
    return OrganizationDomainRepresentationFromJSONTyped(json, false);
}

export function OrganizationDomainRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationDomainRepresentation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'domainName': !exists(json, 'domain_name') ? undefined : json['domain_name'],
        'verified': !exists(json, 'verified') ? undefined : json['verified'],
        'recordKey': !exists(json, 'record_key') ? undefined : json['record_key'],
        'recordValue': !exists(json, 'record_value') ? undefined : json['record_value'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function OrganizationDomainRepresentationToJSON(value?: OrganizationDomainRepresentation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'domain_name': value.domainName,
        'verified': value.verified,
        'record_key': value.recordKey,
        'record_value': value.recordValue,
        'type': value.type,
    };
}

