/* tslint:disable */
/* eslint-disable */
/**
 * Keycloak Account API
 * Derived from the code at https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java 
 *
 * The version of the OpenAPI document: 20.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileMetadataAttributeRepresentation
 */
export interface UserProfileMetadataAttributeRepresentation {
    /**
     * 
     * @type {string}
     * @memberof UserProfileMetadataAttributeRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileMetadataAttributeRepresentation
     */
    displayName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfileMetadataAttributeRepresentation
     */
    required?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfileMetadataAttributeRepresentation
     */
    readOnly?: boolean;
    /**
     * 
     * @type {object}
     * @memberof UserProfileMetadataAttributeRepresentation
     */
    validators?: object;
}

/**
 * Check if a given object implements the UserProfileMetadataAttributeRepresentation interface.
 */
export function instanceOfUserProfileMetadataAttributeRepresentation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserProfileMetadataAttributeRepresentationFromJSON(json: any): UserProfileMetadataAttributeRepresentation {
    return UserProfileMetadataAttributeRepresentationFromJSONTyped(json, false);
}

export function UserProfileMetadataAttributeRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileMetadataAttributeRepresentation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'required': !exists(json, 'required') ? undefined : json['required'],
        'readOnly': !exists(json, 'readOnly') ? undefined : json['readOnly'],
        'validators': !exists(json, 'validators') ? undefined : json['validators'],
    };
}

export function UserProfileMetadataAttributeRepresentationToJSON(value?: UserProfileMetadataAttributeRepresentation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'displayName': value.displayName,
        'required': value.required,
        'readOnly': value.readOnly,
        'validators': value.validators,
    };
}

